[package]
name = "kinode_process_lib"
version = "0.5.7"
edition = "2021"

[dependencies]
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-primitives = "0.6.2"
alloy-transport = { git = "https://github.com/alloy-rs/alloy.git" }
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy.git" }
anyhow = "1.0"
bincode = "1.3.3"
http = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
thiserror = "1.0"
url = "2.4.1"
mime_guess = "2.0"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "efcc759" }
